### ISSUE TITLE
Decide which data we're going to use to give indication of trust

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/Trust-Open-Access#8]
1. Discussed using DOAJ data as primary list of all OA journals. 
2. Seeing if we can use Journal TOC's as list of ALL journals. As seen in #2 
3. Discussed using OASPA publisher list as source of 'trusted" journals
4. Discussed using DOAJ "Seal of approval" as one source of "trusted" journals
5. Other "trusted" lists could include country lists (often countries approve journals to publish in)
6. Could take use suggestions/feedback
7. Will not be using Beal's list for any purpose

Note: In V2 build we only look at page URL for a journal

**Comment by dommitchell** [comment]
My thoughts on this:

(Refer to #9 )

DOAJ as a data source:
- list of all journals with the Tick. Automatically includes the Seal journals.
- list of all applications with the status 'pending', 'in progress', 'ready' or 'submitted'
- list of all journals without the Tick
(I'd like to get @markmacgillivray's input here on how feasible these are.)

OASPA as a data source:
- all pure open access journals belonging to OASPA members. (No hybrids.)

Other data sources:
- CRISTIN? (Norway)
- JournalTOCs: do they filter? Is JTOCs 100% genuine journals?
- other DOAJ sources? https://doajournals.wordpress.com/2014/08/28/some-journals-say-they-are-in-doaj-when-they-are-not/ and https://docs.google.com/spreadsheets/d/183mRBRqs2jOyP0qZWXN8dUd02D4vL0Mov_kgYF8HORM/edit#gid=1650882189 (with a filter?)

**Comment by davidecarroll** [comment]
so, doing things like this is always potentially dangerous 

if we're deciding this, it'll then be based on the opinions and judgements of (now) 3 people and, therefore, subject to the errors of judgement, prejudices and conflicts of interest associated with that. In what has been discussed so far, this approach is seeming to say that only Open Access journals can be trusted. which is not true, there are plenty of traditional journals that can be trusted too. Point 7 says avoiding Beall but honestly, I have to ask myself if the methodology will be any better than Beall's.

on an off-tangent, we aren't really conferring "trust". Trust can only be earned by for example by actions that are consistent with what they say and think. This might be better suited as a way for journals to induce trustworthiness, and by extension enable trust.

anyway, if this is to be decided. it should be impersonal (is this group able to do that?), have prospective and transparent exclusion and inclusion criteria decided by a broadly representative body, be made available for consultation by a focus group or the whole community beforehand, and possibly (i'd prefer to avoid the bureaucracy) backed by academic organizations 

p.s point 5, using countries is a bad idea because of the potentially risk of discrimination by people or technology

**Comment by JosephMcArthur** [comment]
I totally agree with David in that I think we should be careful about the tool suggesting subscriptions journals aren't trusted (as I mentioned in #9 ). 

I don't think we need to be so worried about suggesting using DOAJ and OASPA as sources of trusted Open Access Journals though - this is pretty normal community practice and advice. While I'm sure neither organisation would profess to be free of bias/flaws in how they evaluate journals (as there is of course no perfect way) they're the best we've got and are pretty transparent in how they do things (see criteria [here] (https://doaj.org/application/new) and [here] (http://oaspa.org/membership/membership-criteria/) ). There's processes are very different to Beal.  

I actually suggested country lists as for some regions, they may help combat bias. For example, perfectly good non-english language journals may suffer in primarily english speaking approval processes. However, other lists, which are run by countries which speak that language may be much better at assessing their quality. I don't actually think we should worried too much at the MVP stage, but I wanted to put it down to nudge memories in future. 

I think using the gdoc @dommitchell mentions would also be useful and I'd be open to using that as a data source. 

@vesko-ski is assessing what we can get from Journal TOCs. It doesn't actually matter that much if they're genuine as it should be used only as the widest possible net of journals + their URLs (useful for giving responses).

**Comment by vesko-ski** [comment]
Using the Journal TOCs API, it is possible to get a list of journals and their URL. They have collection of over 26,000 journals, which I assume it is the widest possible net of journals/URLs we can get.

In terms of the gdoc that @dommitchell mentions, how are we going to use it? I assume if the journal is tagged as "Journal not adhering to Best Practice" or "Suspected editorial misconduct by publisher" we can simply flag them as red. However, "Website URL no longer works" or "Ceased publishing" would not necessarily mean that the journal is not trusted and should be flagged with red (I assume).

Also, the gdoc does not specify any URLs, so we would have to match the URLs with some of our current data. By the looks of it, most of the journals in the list are listed in Journal Tocs, so I guess that will be fine.

For getting a list of journals that are NOT trusted, what do you think of this source: http://scholarlyoa.com/individual-journals/

**Comment by dommitchell** [comment]
> In terms of the gdoc that @dommitchell mentions, how are we going to use it? I assume if the journal is tagged as "Journal not adhering to Best Practice" or "Suspected editorial misconduct by publisher" we can simply flag them as red. However, "Website URL no longer works" or "Ceased publishing" would not necessarily mean that the journal is not trusted and should be flagged with red (I assume).

Yep, hence I was hoping you might be able to establish some sort of filter because some of those in the list just simply aren't online any more. I'm hoping that journals marked with the following could be used: 

Journal is no longer Open Access;
Editorial misconduct;
Suspected editorial misconduct by publisher;
Journal not adhering to Best practice.

> For getting a list of journals that are NOT trusted, what do you think of this source: http://scholarlyoa.com/individual-journals/

We'd really rather avoid that list altogether. It is too subjective for a project like this.

**Comment by JosephMcArthur** [comment]
Same as #9
